const Projects = [
  {
    name: 'RE:Public',
    language: ['JavaScript'],
    image: 'REPublic',
    link: 'https://github.com/dustinpezley/re-public-v2',
    id: 'republic',
    type: ['Front-end'],
    appLink: 'https://dustinpezley.github.io/re-public-election-info/',
    description:
      'Knowing your legislators and elected officials is an invaluable asset to your advocacy efforts at any level of government. Personal history informs public policy decisions and provides information that you can use to connect with those elected officials. RE:Public is a search tool to find your elected officials, their contact information, basic financial information, and their top contributors. Knowledge is power, and RE:Public is a tool that puts power in your hand.',
  },
  {
    name: 'Text Editor',
    language: ['JavaScript', 'PWA'],
    image: 'Text-Editor',
    link: 'https://github.com/dustinpezley/pwa-text-editor',
    id: 'text-editor',
    type: ['Full-stack'],
    appLink: 'https://texteditor-5fmw.onrender.com',
    description:
      'Simple text editor with JavaScript highlighting that can be run online or offline. Text will persist on reload.',
  },
  {
    name: 'Tech Blog',
    language: ['JavaScript', 'MySQL'],
    image: 'Tech-Blog',
    link: 'https://github.com/dustinpezley/the-tech-blog',
    id: 'tech-blog',
    type: ['Full-stack'],
    appLink: 'https://techblog-pl88.onrender.com',
    description:
      'A simple CMS-style blog with user authentication and posting and commenting functionality. Database is currently seeded with test data.',
  },
  {
    name: 'Team Profile Generator',
    language: ['JavaScript'],
    image: 'Team-Profile-Generator',
    link: 'https://github.com/dustinpezley/team-profile-generator',
    id: 'team-profile-generator',
    type: ['Back-end'],
    appLink: '',
    description:
      'This is a Node-driven application utilizing Inquirer. It produces a styled HTML page with the team hierarchy listed, including names, titles, employee numbers, github profiles, etc.',
  },
  {
    name: 'README Generator',
    language: ['JavaScript'],
    image: 'README',
    link: 'https://github.com/dustinpezley/README-Generator',
    id: 'readme',
    type: ['Back-end'],
    appLink: '',
    description:
      'Producing a README is a vital part of development work as it is the front door to your initiatives. This tool streamlines that process using best practices for README format.',
  },
  {
    name: 'Weather Dashboard',
    language: ['JavaScript'],
    image: 'Weather-Dashboard',
    link: 'https://github.com/dustinpezley/weather_dashboard',
    id: 'weather-dashboard',
    type: ['Front-end'],
    appLink: 'https://dustinpezley.github.io/weather_dashboard/',
    description:
      'Search for a city, and you will be returned the current conditions in that city, as well as a five-day forecast. Additional information includes wind speed, humidity, and current UV index, xolor-coded with the EPA standards.',
  },
  {
    name: 'Photo Portfolio',
    language: ['React-JS', 'JavaScript'],
    image: 'Photo-Portfolio',
    link: 'https://github.com/dustinpezley/photo-port',
    id: 'photo-portfolio',
    type: ['Full-stack'],
    appLink: 'https://dustinpezley.github.io/photo-port/',
    description: 'Example of a React-based photographer portfolio.',
  },
  {
    name: 'Social Media API',
    language: ['JavaScript', 'NoSQL'],
    image: 'Social-Media',
    link: 'https://github.com/dustinpezley/rapt-social-media',
    id: 'social-media-api',
    type: ['Back-end'],
    appLink: '',
    description:
      'This is a demonstration of a simple back-end set up for a social media app utilizing NoSQL calls through MongoDB.',
  },
  {
    name: 'Contact Cards',
    language: ['JavaScript', 'ExpressJS'],
    image: 'Contact-Card',
    link: 'https://github.com/dustinpezley/contact-card',
    id: 'contact-card',
    type: ['Full-stack'],
    appLink: 'https://contactcard-6glp.onrender.com',
    description:
      'Web app utilizing ExpressJS and IndexedDB for keeping track of contact information.',
  },
  {
    name: 'Note Taker',
    language: ['JavaScript', 'ExpressJS'],
    image: 'Note-Taker',
    link: 'https://github.com/dustinpezley/note-taker',
    id: 'note-taker',
    type: ['Full-stack'],
    appLink: 'https://note-taker-62mp.onrender.com',
    description:
      'This is a simple productivity app to take notes and save them in the cloud.',
  },
  {
    name: 'APPly',
    language: ['JavaScript', 'NodeJS', 'ExpressJS', 'React-JS', 'MongoDB', 'GraphQL'],
    image: 'APPly',
    link: 'https://github.com/sarameadows/APPly',
    id: 'apply',
    type: ['Full-stack'],
    appLink: '',
    description: 'Web app for saving job searches from multiple sources.',
  },
  {
    name: 'Procedural Map',
    language: ['JavaScript', 'NodeJS', 'ThreeJS'],
    image: 'Procedural-Map',
    link: 'https://github.com/dustinpezley/procedural-map',
    id: 'procedural-map',
    type: ['Front-end'],
    appLink: 'https://dustinpezley.github.io/procedural-map/',
    description:
      'ThreeJS project to create a random map of hexagons with a few added details.',
  },
  {
    name: 'Car Physics',
    language: ['JavaScript', 'NodeJS', 'ThreeJS', 'React-JS', 'CannonJS'],
    image: 'Car-Physics',
    link: 'https://github.com/dustinpezley/car-physics',
    id: 'car-physics',
    type: ['Front-end'],
    appLink: 'https://dustinpezley.github.io/car-physics/',
    description:
      'Car racing game with keyboard controls (WASD) and wacky physics.',
  },
];

export default Projects;
